# Generated by Django 5.2.6 on 2025-10-01 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arzt',
            name='nachname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Gruppen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('arzt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gruppen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
